export const queryKeys = {
  travelSurvey: "travelSurvey",
  surveyProgress: "surveyProgress",
  profile: "profile",
  placeLikedList: "placeLikedList",
  placeSearchList: "placeSearchList",
  makingNoteProfile: "makingNoteProfile",
  makingNoteCourse: "makingNoteCourse",
  makingNoteComment: "makingNoteComment",
  makingNoteCoordinate: "makingNoteCoordinate",
  makingNoteCompanionList: "makingNoteCompanionList",
  makingNoteCourseDistance: "makingNoteCourseDistance",
  makingNotePlacesRecommended: "makingNotePlacesRecommended",
  travelNoteDetailInfo: "travelNoteDetailInfo",
  travelNoteDetailComment: "travelNoteDetailComment",
  travelNoteDetailCourseInfo: "travelNoteDetailCourseInfo",
  travelNoteDetailLike: "travelNoteDetailLike",
  travelNoteCoordinate: "travelNoteCoordinate",
  travelNoteRecommendedNote: "travelNoteRecommendedNote",
  placeDetailInfo: "placeDetailInfo",
  placeDetailAdditionalInfo: "placeDetailAdditionalInfo",
  placeDetailLike: "placeDetailLike",
  placeDetailComment: "placeDetailComment",
  recommendNoteList: "recommendNoteList",
  recommendPlaceList: "recommendPlaceList",
  weeklyNoteList: "weeklyNoteList",
  recentlyMostVisitedPlaceList: "recentlyMostVisitedPlaceList",
  myTravelNote: "myTravelNote",
  travelNoteLikeList: "travelNoteLikeList",
  memberProfile: "memberProfile",
  memberPublicTravelNote: "memberPublicTravelNote",
  memberPlaceLikedList: "memberPlaceLikedList",
  memberTravelNoteLikedList: "memberTravelNoteLikedList",

  searchPublicTravelNote: "searchPublicTravelNote",
  searchPlace: "searchPlace",
  searchMember: "searchMember",

  totalTravelNoteCount: "totalTravelNoteCount",

  photodigmInfo: "photodigmInfo",
  photodigmPictureList: "photodigmPictureList",
  photodigmFrame: "photodigmFrame",
  myPhotodigmList: "myPhotodigmList",

  accommodationList: "accommodationList",
  restaurantList: "restaurantList",

  myTravelNoteCount: "myTravelNoteCount",
  myFeedTravelNote: "myFeedTravelNote",
  selectedFeedTravelNote: "selectedFeedTravelNote",

  placeProfile: "placeProfile",

  feedList: "feedList",
  feedDetailProfile: "feedDetailProfile",
  feedDetailCommentCount: "feedDetailCommentCount",
  feedDetailLikeState: "feedDetailLikeState",
  feedCommentList: "feedCommentList",

  modifyFeedProfile: "modifyFeedProfile",
  myFeedList: "myFeedList",

  followState: "followState",
  followList: "followList",
  followCount: "followCount",
};
